---

- name: Create Docker network
  docker_network:
    name: my_app_network
    driver: bridge
    state: present
    ipam_config:
      - subnet: "192.168.1.0/24"
  vars:
    ansible_python_interpreter: /usr/bin/python3
