---
- name: Docker login
  docker_login:
    username:
    password: 

# Launch application container
- name: Launch application container
  docker_container:
    name: my-api
    image: zayed13/tp-devops-simple-api
    state: started
    env:
      DATABASE_URL: postgres://XXXX:XXXX@my-db:5432/XXXX
    networks: [{"name" : "my_app_network"}]
      
